services:
  # Backend
  - type: web
    name: bosque-inn-api
    env: node
    plan: free # <--- Explicitly use the free tier
    rootDir: server
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: PORT
        value: 3001
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_SERVICE_ROLE_KEY
        sync: false
